Do not crash on redirected items when formatting grouping links
Formatting the grouping link of an Item line
was crashing when the grouping was a redirect.

```
pywikibot.exceptions.IsRedirectPageError: Page [[wikidata:Q120133106]] is a redirect page.
CRITICAL: Exiting due to uncaught exception <class 'pywikibot.exceptions.IsRedirectPageError'>
```