Replace pywikibot's ReferringPageGenerator with Page.getReferences
This is not working anymore with the pywikibot upgrade (de296cd) [1],
and to be fair we had been warned of it for a while now [2].

[1] Error
```
AttributeError: module 'pywikibot.pagegenerators' has no attribute 'ReferringPageGenerator'
```

[2] Warning
```
WARNING: integraality/pages_processor.py:62:
FutureWarning: pywikibot.pagegenerators.ReferringPageGenerator
is deprecated for 12 months and 27 days;
use Page.getReferences(follow_redirects=False) instead.
```