Do not crash when there are no results for a property
When there are no items returned for a property (by `get_property_info`),
typically because the thresholds are too high, then this was crashing with
```
AttributeError: 'NoneType' object has no attribute 'get'
```

Now we just default to 0 if that is the case.