Fix crash for unknown value for grouping by year
Support for unknown value grouping (added in 8dbc099) was not
working well together with the grouping by year (added in 0a8e7fb),
resulting in a crash [1].

This is because using YEAR on unknown value results in an empty value.

[1] Stack trace:
```
File "./property_statistics.py", line 313, in get_grouping_information if
resultitem.get('grouping').startswith(self.UNKNOWN_VALUE_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Follow-up to T236590 and T273226