Fix incorrect f-string syntax under Python 3.5
This line was introduced in d4fa3637 using f-strings,
which the Toolforge Python3.5 environment does not support.

See also 2abc519e.

```
logging.info(f"Could not retrieve label for {grouping}")
SyntaxError: invalid syntax
```