Fix assertion in test_make_stats_for_no_group
Tests were failing on Travis-CI with:
```
AttributeError: 'function' object has no attribute 'assert_called_once'
```

In 9bd4160, we added a unit test for `make_stats_for_no_group`,
with an assertion using `assert_called_once`. However, this was
only introduced in Python 3.6, and tests run on 3.5.

Change the test to use `assert_called_once_with`.

(Note how autospeccing saved the day here)