Also catch ServerError to handle WDQS timeouts
The Wikidata Query Service will timeout if being
asked too complex a query (or a broken query).

We catch WDQS timeouts when fetching groupings since 7e3343a5731,
by catching `pywikibot.exceptions.TimeoutError`,

However we now have instances of `ServerError` being raised [1],
so let's also catch that exception.

Also add unit-test covering it.

[1] Traceback:
```
File "app.py", line 29, in update    processor.process_one_page(page_title)
File "./pages_processor.py", line 197, in process_one_page    self.process_page(page)
File "./pages_processor.py", line 125, in process_page    output = stats.retrieve_and_process_data()
File "./property_statistics.py", line 236, in retrieve_and_process_data    groupings = self.retrieve_data()
File "./property_statistics.py", line 261, in retrieve_data    groupings = self.get_grouping_information()
File "./property_statistics.py", line 72, in get_grouping_information    return self.grouping_configuration.get_grouping_information(self.selector_sparql)', '
File "./grouping.py", line 130, in get_grouping_information    queryresult = sq.select(query)', '
File "/pywikibot/data/sparql.py", line 114, in select    data = self.query(query, headers=headers)', '
File "/pywikibot/data/sparql.py", line 158, in query    self.last_response = http.fetch(url, headers=headers)
File "/pywikibot/comms/http.py", line 452, in fetch    callback(response)
File "/pywikibot/comms/http.py", line 328, in error_handling_callback    raise ServerError(response)
pywikibot.exceptions.ServerError: HTTPSConnectionPool(host='query.wikidata.org', port=443): Read timed out. (read timeout=45)
```

Bug: T384882
Bug: T278156